README.md
lib/safe-pg-migrations/base.rb
lib/safe-pg-migrations/configuration.rb
lib/safe-pg-migrations/plugins/blocking_activity_logger.rb
lib/safe-pg-migrations/plugins/statement_insurer.rb
lib/safe-pg-migrations/plugins/verbose_sql_logger.rb
lib/safe-pg-migrations/railtie.rb
test/safe_pg_migrations_test.rb

Hey !
As PG 11 handle `add_column` with a default non-volatile value gracefully, we do not need the backfill trick anymore.
Most of our index creations on large tables in the last months were unsuccessful because of a lock timeout. As the only way to create indexes with **Safe PG Migrations** is concurrently, being locked for more than `5s` does not harm, so we increased it to `30s`.
To demystify **Safe PG Migrations** inner working, and to better investigate migration failure in production, we added a way to log every SQL query happening in a migration. This is also useful in development to get a better grasp of what is going on for high-level statements like `add_reference`
A user would expect the gem to do not anything when disabled. But it was more of a `wrap_in_transaction` setting, …

Handle PG 11, change index operations lock timeout, plus various improvements

---

.travis.yml
lib/safe-pg-migrations/plugins/statement_insurer.rb
test/safe_pg_migrations_test.rb

Travis was broken because psql 9.4 (that we used) is no longer supported by travis. This PR: 
* Uses psql 9.6 in travis (9.4 is no longer supported neither by travis nor APT, I haven't looked further)
* Fixes some rubocop
* Skips rubocop for the add_column method (I'll create a ticket for that)

Fixing travis.yml

---

lib/safe-pg-migrations/plugins/blocking_activity_logger.rb
test/safe_pg_migrations_test.rb

Adds the duration of a blocking query. 
The result will now look like this: 
```== 8128 : migrating ===========================================================
-- add_column(:users, :email, :string)
-> Lock timeout.
-> Statement was being blocked by the following query:
-> 
->   BEGIN; SELECT 1 FROM users -- [started at 2020-11-18 18:30:01 +0000, 1 second ago]
-> Beware, some of those queries might run in a transaction. In this case the locking query might be located elsewhere in the transaction
-> 
-> Retrying in 1 seconds...
-> Retrying now.
-> 1.5153s
== 8128 : migrated (1.5243s) ==================================================
```

Add duration for blocking queries

---

lib/safe-pg-migrations/plugins/idem_potent_statements.rb
test/create_table_test.rb
test/safe_pg_migrations_test.rb
test/test_helper.rb

When doing this migration: 
```rb
class CreateUserTable < ActiveRecord::Migration
def change
create_table(:users) do |t|
t.string :email, index: true
end
end
end
```
`ActiveRecord` will first create the table, then create the indexes. However, if a timeout happens while creating the index, we would not detect that the table creation was not completed, as we only check for table existence. 
* Make create_table with table idempotent
* `force` option will also recreate the table (even if it already exists)

Make create_table idempotent for indexes as well

---

README.md
lib/safe-pg-migrations/base.rb
lib/safe-pg-migrations/plugins/useless_statements_logger.rb
test/safe_pg_migrations_test.rb
test/useless_statement_logger_test.rb

A few elements are not needed when using safe-pg-migrations: 
* `disable_ddl_transactions!`
* `add_index` or `remove_index` with `:concurrently` algorithm. 
This PR warns the user when he uses these options.

Add warnings when useless statement are used

---

README.md
lib/safe-pg-migrations/configuration.rb
lib/safe-pg-migrations/plugins/blocking_activity_logger.rb
lib/safe-pg-migrations/plugins/statement_insurer.rb
lib/safe-pg-migrations/plugins/statement_retrier.rb
test/create_table_test.rb
test/safe_pg_migrations_test.rb

Index create/drop are blocked by any active statement that was running before the creation/removal started.

Set lock_timeout to 0 for index create/drop

---

lib/safe-pg-migrations/plugins/statement_insurer.rb
test/create_table_test.rb

Concurrently algorithm during table creation is useless and makes the migrations much longer.

Not adding index concurrently if table creation

---

README.md

`safe-pg-migrations` make an extensive use of `SET` (with e.g.  `statement_timeout`) and `disable_ddl_transaction!`. Those two don't play well together when used via PgBouncer in transactional pooling mode.
Transactional pooling mode is the default for server-side (Postgres-side) PgBouncer installation on Heroku.
`SET statement_timeout`/`CREATE INDEX CONCURRENTLY` and reset of `statement_timeout` could run in three different server connections.  Because of `disable_ddl_transaction!`. There are two problems here:
- unsettling `statement_timeout` has no effect on `CREATE INDEX CONCURRENTLY`'s timeout if they are executed in different server connections
- we leave a connection hanging in PgBouncer's pool with unset `statement_timeout`
Fixes #34

Add PgBouncer precautionary note to README

---

lib/safe-pg-migrations/plugins/statement_insurer.rb
test/safe_pg_migrations_test.rb

One of the performance improvements in Postgres 11 was executing an `ADD COLUMN ... NOT NULL` without needing a table rewrite. This is now a safe operation in PG11+, and we can avoid adding backwards-compatible safe version with a statement timeout that can fail in some cases.
https://www.postgresql.org/docs/release/11.0/
Fixes #37.

Execute NOT NULL with ADD COLUMN in PG11+

---

README.md

Let's include [Stop worrying about PostgreSQL locks in your Rails migrations](https://medium.com/doctolib/stop-worrying-about-postgresql-locks-in-your-rails-migrations-3426027e9cc9), it defines perfectly our motivations.

Add article in readme

---

README.md
lib/safe-pg-migrations/configuration.rb
lib/safe-pg-migrations/plugins/blocking_activity_logger.rb
test/safe_pg_migrations_test.rb

Implements the possibility to prevent blocking queries form being logged & instead display informations about the lock itself, in order to avoid potentially displaying private user informations

TT-3754: New option to hide raw SQL queries in blocking queries logger. 

---

lib/safe-pg-migrations/base.rb
lib/safe-pg-migrations/plugins/idempotent_statements.rb
test/add_foreign_key_test.rb
test/safe_pg_migrations_test.rb

It's more commonly used as a single English word
https://en.wiktionary.org/wiki/idempotent rather than two Latin words.

Rename Idem Potent to Idempotent

---

lib/safe-pg-migrations/base.rb
lib/safe-pg-migrations/plugins/legacy_active_record_support.rb
lib/safe-pg-migrations/plugins/old_rails_version_support.rb
test/add_foreign_key_test.rb

Some methods have changed the number or argument between version 5.2 and version 6: 
`foreign_key_exists?` from
```rb
def foreign_key_exists?(from_table, options_or_to_table = {})
```
https://github.com/rails/rails/blob/5-2-stable/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L1010
to 
```rb
def foreign_key_exists?(from_table, to_table = nil, **options)
```
https://github.com/rails/rails/blob/main/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L1151
And `validate_foreign_key` from 
```rb
def validate_foreign_key(from_table, options_or_to_table = {})
```
https://github.com/rails/rails/blob/5-2-stable/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb#L626
To
```rb
def …
```

Fix support for ActiveRecord < 6

---

lib/safe-pg-migrations/plugins/blocking_activity_logger.rb

In older version of ActiveRecord, time is returned as a string and not a time.

Fix issue #51: start_time may be a string

---

lib/safe-pg-migrations/plugins/legacy_active_record_support.rb

Hi there! Using Ruby 2.7.4, the following warnings pop up since these methods are using keywords instead of splats:
```
/Users/sunny/code/safe-pg-migrations/lib/safe-pg-migrations/plugins/legacy_active_record_support.rb:5: warning: Skipping set of ruby2_keywords flag for validate_foreign_key (method accepts keywords or method does not accept argument splat)
/Users/sunny/code/safe-pg-migrations/lib/safe-pg-migrations/plugins/legacy_active_record_support.rb:11: warning: Skipping set of ruby2_keywords flag for foreign_key_exists? (method accepts keywords or method does not accept argument splat)
```

Fix ruby2_keywords flag warning

---

lib/safe-pg-migrations/plugins/idempotent_statements.rb
lib/safe-pg-migrations/plugins/legacy_active_record_support.rb

IndexDefinition, that we rely on for `idempotent_statement#add_index` was introduced in Rails 6.1.
This PR adds compatibility with older versions. 
Fixing #71

[BUGFIX] Fix compatibility with Rails < 6.1

---

lib/safe-pg-migrations/plugins/legacy_active_record_support.rb

Reverts doctolib/safe-pg-migrations#70
Broken compatibility with activerecord 5.2 and ruby 2.6
https://github.com/doctolib/safe-pg-migrations/runs/5374516778

Revert "Fix ruby2_keywords flag warning"

---

.github/workflows/continuous-integration-workflow.yml
gemfiles/activerecord60.gemfile
lib/safe-pg-migrations/plugins/statement_insurer.rb

Hello there,
We detected there is an error when we use `ruby 3.0` and `ActiveRecord 6.0` 
CF error: 
```ruby
StatementInsurerTest#test_add_belongs_to:
StandardError: An error has occurred, all later migrations canceled:
wrong number of arguments (given 3, expected 2)
/home/runner/work/safe-pg-migrations/safe-pg-migrations/lib/safe-pg-migrations/plugins/statement_insurer.rb:67:in `add_index'
/home/runner/work/safe-pg-migrations/safe-pg-migrations/lib/safe-pg-migrations/plugins/useless_statements_logger.rb:15:in `add_index'
/home/runner/work/safe-pg-migrations/safe-pg-migrations/vendor/bundle/ruby/3.0.0/gems/activerecord-6.0.5.1/lib/active_record/connection_adapters/abstract/schema_definitions.rb:570:in `index'
/home/runner/work/safe-pg-migrations/safe-pg-migrations/vendor/bundle/ruby/3.0.0/ …
```

Fix Add index for ruby 3.0

---

lib/safe-pg-migrations/base.rb
lib/safe-pg-migrations/plugins/idempotent_statements.rb
lib/safe-pg-migrations/plugins/index_definition_polyfill.rb
lib/safe-pg-migrations/plugins/legacy_active_record_support.rb
test/idempotent_statements_test.rb

Such a migration: 
```rb
class RemoveDocumentsFkFromInstantMessagingMessages < ActiveRecord::Migration[7.0]
def change
remove_foreign_key :messages, :documents
add_foreign_key :messages, :documents, column: :prescription_id
end
end
```
is not idempotent: if `add_foreign_key` fails, the migration cannot be run again because the foreign key on messages refering document_id is already deleted. 
A safer approach is this one:  
```rb
class RemoveDocumentsFkFromInstantMessagingMessages < ActiveRecord::Migration[7.0]
def change
if foreign_key_exists?(:messages, :documents)
remove_foreign_key :messages, :documents
end
add_foreign_key :messages, :documents, column: :prescription_id
end
end
```
---
safe-pg-migrations can help here, this PR is bringing idempotence to remove_foreign_key so that the …

Add remove_foreign_key idempotent

---

.github/workflows/continuous-integration-workflow.yml

To get rid of the following warning:
`Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/checkout`
As `actions/checkout` uses Node.js 16 since `v3` release.

Bump actions/checkout

---

lib/safe-pg-migrations/helpers/blocking_activity_formatter.rb
lib/safe-pg-migrations/helpers/blocking_activity_selector.rb
lib/safe-pg-migrations/plugins/blocking_activity_logger.rb
test/blocking_activity_logger_test.rb
test/statement_retrier_test.rb
test/test_helper.rb
test/verbose_sql_logger_test.rb

Blocking activity is now compatible with add_index and remove_index, where locks are not being trigerred. 
Also includes the blocking activity PID when the verbose mode is set.

Add logs when add_index is taking too long

---

lib/safe-pg-migrations/plugins/statement_retrier.rb

Only a few statements are allowed to retry (up to 5 times) drop_table is not one of them.
- Added `drop_table` to the list of retriable statements
TT-17552

Adding drop_table to the list of retriable statements

---

lib/safe-pg-migrations/base.rb
lib/safe-pg-migrations/configuration.rb
lib/safe-pg-migrations/plugins/statement_insurer.rb
test/IdempotentStatements/idempotent_statements_test.rb
test/StatementInsurer/statement_insurer_test.rb
test/blocking_activity_logger_test.rb
test/safe_pg_migrations_test.rb
test/test_helper.rb
test/verbose_sql_logger_test.rb

When statement timeouts and lock timeouts have the same value, statement timeout will be raised in priority. Some mechanics (blocking activity loggers for instance) rely on lock timeouts being raised. 
This fix reduces the lock timeout by 1%, so that it is raised before the statement timeout

Add small margin to lock timeout, otherwise it is hidden by statement timeouts

---

README.md
lib/safe-pg-migrations/configuration.rb
test/safe_pg_migrations_test.rb

In some case, we want to be able to configure the lock timeout more precisely, which was not available before. 
This PR introduce the new configuration `lock_timeout` which allows users to configure the lock timeout. Default value is unchanged (99% of the safe_timeout)

Make lock_timeout configurable

---

lib/safe-pg-migrations/base.rb
lib/safe-pg-migrations/helpers/blocking_activity_formatter.rb
lib/safe-pg-migrations/helpers/logger.rb
lib/safe-pg-migrations/plugins/blocking_activity_logger.rb
lib/safe-pg-migrations/plugins/idempotent_statements.rb
lib/safe-pg-migrations/plugins/statement_insurer.rb
lib/safe-pg-migrations/plugins/statement_insurer/add_column.rb
lib/safe-pg-migrations/plugins/statement_retrier.rb
lib/safe-pg-migrations/plugins/useless_statements_logger.rb
test/blocking_activity_logger_test.rb
test/useless_statement_logger_test.rb

I only noticed the bug because I was refactoring logs (for a later PR) into a dedicated module, which is the main point of this PR

Bugfix: UselessStatementLogger now warns when disable_ddl_transaction is called

---

.github/workflows/continuous-integration-workflow.yml
Gemfile
Gemfile.lock
README.md
gemfiles/without_strong_migrations.gemfile
lib/safe-pg-migrations/base.rb
lib/safe-pg-migrations/configuration.rb
lib/safe-pg-migrations/plugins/statement_insurer/add_column.rb
lib/safe-pg-migrations/plugins/strong_migrations_integration.rb
lib/safe-pg-migrations/railtie.rb
test/StatementInsurer/add_column_test.rb
test/strong_migration_integration_test.rb
test/test_helper.rb
test/verbose_sql_logger_test.rb

`add_column` with `default_value_backfill: :update_in_batches` can be dangerous on big tables. To avoid unwanted long migrations, **Safe PG Migrations** does not automatically mark this usage as safe when used with `strong-migrations`, usage of `safety_assured` is required.
It is also possible to set a threshold for the table size, above which the migration will fail. This can be done by setting the `default_value_backfill_threshold:` option in the configuration.

Introduce `default_value_backfill_threshold:` config to avoid unwanted long migration when adding a column with `:update_in_batches`

---

README.md
lib/safe-pg-migrations/plugins/idempotent_statements.rb
lib/safe-pg-migrations/plugins/statement_insurer.rb
test/IdempotentStatements/drop_table_test.rb
test/StatementInsurer/drop_table_test.rb
test/StatementInsurer/remove_column_test.rb

Dropping a table can be difficult to achieve in a small amount of time if it holds several foreign keys to busy tables.
To remove the table, PostgreSQL will have to acquire an access exclusive lock on all the tables referenced by the foreign keys.
To solve this issue, **Safe Pg Migrations** will drop the foreign keys before dropping the table.
---
**NOTE**
Dropping a table is a dangerous operation by nature. **Safe Pg Migrations** will not prevent the deletion of a table which
would still be in use.
---

drop_table: Remove foreign keys before removing a column

---

Gemfile.lock
lib/safe-pg-migrations/version.rb

We are upgrading the gem to `v3.0.0` as the dependencies have change, notably: 
- The support of `ActiveRecord 7.1` and above 
- The drop of `ActiveRecord 6.0` (support starts now at `6.1`)
- The drop of `Ruby 2.X` versions

Upgrade gem versions to 3.0.0

---

lib/safe-pg-migrations/plugins/statement_insurer.rb
test/StatementInsurer/statement_insurer_test.rb

We had a bug that forbid to have more than one args for `create_table`
This was due to a missing update of `create_table` in `statement_insurer.rb`
we also enrich one test to spot those kind of issue in the future.

Fix args bug for create_table

---

lib/safe-pg-migrations/helpers/batch_over.rb

It can help performance by avoiding table lookups and reducing network usage.
For the potential gains, see benchmark: https://github.com/doctolib/safe-pg-migrations/pull/136#issuecomment-1963847811

BatchRecord: select primary keys instead of full records

---

lib/safe-pg-migrations/plugins/statement_insurer/change_column_null.rb
test/StatementInsurer/change_column_null_test.rb

When changing a column to non-null, we try to look for existing check constraints on the column based on the expression. There seems to however be a typo, and currently, we're taking the first check constraint, whatever it is, from the table.
This PR fixes this, by fixing the typo, and adds a test, which currently fails in master.

Fix check used when adding non null constraint

---

README.md
lib/safe-pg-migrations/configuration.rb
lib/safe-pg-migrations/plugins/statement_retrier.rb
test/statement_retrier_test.rb

Many times the background migrations failed just because the lock timeout was too short.
In this PR we increase the lock_timeout gradually upon retries to help make the migration pass.

Tt 23249 increment lock_timeout gradually to reduce failing migrations

---

lib/safe-pg-migrations/helpers/batch_over.rb

We revert some changes that were only selecting the PK for the BatchRecord. 
In some cases it could cause issue when trying to access other attributes

BatchRecord: Revert selecting only PK

---

.github/workflows/continuous-integration-workflow.yml
Gemfile.lock
gemfiles/activerecord61.gemfile
gemfiles/activerecord70.gemfile
lib/safe-pg-migrations/configuration.rb
lib/safe-pg-migrations/helpers/pg_helper.rb
lib/safe-pg-migrations/plugins/statement_retrier.rb
test/statement_retrier_test.rb

The retrier was modifying the lock_timeout config but:
- If there was a success the settings might be affected for other migrations 
- the `lock_timeout` was not really changed on DB side

fix the increase lock timeout on retry

---

Gemfile.lock
lib/safe-pg-migrations/version.rb

Upgrade gem versions to 3.1.2 following a fix: 
- Retry was not increasing the lock_timeout as expected

Upgrade gem versions to 3.1.2

---

lib/safe-pg-migrations/helpers/blocking_activity_formatter.rb

We had issue logging blocking queries because for unknown reason we did not retrieved `xact_start` from `pg_stat_activity`.
We were trying to parse `nil` as a `string`.. 
Now we  will display `'unknown'` in this case

Handle cases when the blocking query xact_start is null (for logging)

---

lib/safe-pg-migrations/helpers/blocking_activity_formatter.rb
test/blocking_activity_logger_test.rb

There were an issue when we retrieve blocking query without a start_date (xact_start)
A fix has been done but only partially fix the issue (on verbose mode only) 
We decided to modify the `format_start_time` implementation instead + add a dedicated test fo blocking queries logger

Fix format_start_time implementation
